### PR TITLE
Mavenify

### PR DESCRIPTION
**Pull request by hawkfalcon**
If you want, allow it to be built by maven (e.g. mvn clean package)

### CODE REVIEW

**Comment by hawkfalcon** [comment]
I didn't mean to include the RGB commit in this PR, but if you want it go ahead :)

**Comment by hawkfalcon** [comment]
@scruffyboy13 you have the structure right now, just copy my pom.xml and you should have maven lol (to build it easier)

**Comment by scruffyboy13** [comment]
I'll be real, I meant to reply to this but kinda forgot about it. I'll add the pom.xml file now.

**Comment by hawkfalcon** [comment]
👍

**Pull request closed without merging**
